apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-chrisjoyce-io-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-chrisjoyce-io-deployment
  template:
    metadata:
      labels:
        name: api-chrisjoyce-io-deployment
    spec:
      containers:
      - name: api-chrisjoyce-io-app
        image: christopherjoyce/api.chrisjoyce.io
        ports:
          - name: http
            containerPort: 3000
            hostPort: 3000
            protocol: TCP
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
